version: "2"
services:
    web:
        tty: true
        stdin_open: true
        build: .
        volumes:
            - ./:/app
        command: "/bin/bash"
        ports:
            - "3000:3000"
